version: '3.8'

services:
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile.stable
    container_name: ecommerce-clothes
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ecommerce-network

  # Optional: Add a development service for hot reloading
  ecommerce-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ecommerce-clothes-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge 